INC_SRC = 'src/InC/'
TICS_PER_MINUTE = 400 # sixteenth notes
JSON_FILENAME = 'src/InC.json'
NUM_PLAYERS = 4
TEMPLATE_DIR = 'web/template/'
MAX_MESSAGE_SIZE = 8192
OCCAM_SERVERS = [('127.0.0.1', 57117)]